controllers/GameController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Users;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;


class GameController extends AppController
{


  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['lotery'],
        'rules' => [
          [
            'actions' => ['lotery'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'logout' => ['post', 'get'],
        ],
      ],
    ];
  }


  /**
   * @return string
   */
  public function actionLotery()
  {
    return $this->render('lotery');
  }


  /**
   * @return string - result of the game
   */
  public function actionGetlotery()
  {
    $user = Users::findOne(Yii::$app->user->identity->getId());

    $rate = +$_POST['rate'];
    $rand = mt_rand(1, 8);
    $data[0] = $rand;

    if ($user->balance - $rate > 0) {
      if ($rate >= 2) {
        if ($_POST['numberBitcoin'] != $rand) {
          $data[1] = 'no_win';
          $user->balance = $user->balance - $rate;
        } else {
          $data[1] = 'win';
          $user->balance = $user->balance + $rate * 2;
        }
        $user->save();
      } else {
        $data[1] = 'small_bet';
      }
    } else {
      $data[1] = 'no_many';
    }

    $data = json_encode($data);
    echo $data;
  }

//  public function actionRole() {
//    $admin = Yii::$app->authManager->createRole('admin');
//    $admin->description = 'Администратор';
//    Yii::$app->authManager->add($admin);
//
//    $user = Yii::$app->authManager->createRole('user');
//    $user->description = 'Пользователь';
//    Yii::$app->authManager->add($user);
//
//    $ban = Yii::$app->authManager->createRole('banned');
//    $ban->description = 'Заблокирован';
//    Yii::$app->authManager->add($ban);

//    $permit = Yii::$app->authManager->createPermission('canAdmin');
//    $permit->description = 'Право на вход в админку';
//    Yii::$app->authManager->add($permit);

//    $role_a = Yii::$app->authManager->getRole('admin');
//    $role_b = Yii::$app->authManager->getRole('user');
//    $role_c = Yii::$app->authManager->getRole('banned');
//    $permit = Yii::$app->authManager->getPermission('canAdmin');
//    Yii::$app->authManager->addChild($role_a, $permit);

//    $userRole = Yii::$app->authManager->getRole('admin');
//    Yii::$app->authManager->assign($userRole, 1);
//    return '132';
//  }

}

controllers/SupportController.php
<?php
/**
 * Created by PhpStorm.
 * User: chvs
 * Date: 25.08.2017
 * Time: 22:23
 */

namespace app\controllers;


class SupportController extends AppController
{

  public function actionSupport()
  {
    return $this->render('support');
  }

}

controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: chvs
 * Date: 25.08.2017
 * Time: 22:34
 */

namespace app\controllers;

use app\models\Payment;
use app\models\User;
use app\models\Users;
use app\models\Support;
use Yii;
use app\models\LoginForm;
use app\models\RegistrUser;

class UserController extends AppController
{

  /**
   * User Authorization
   * @return string|\yii\web\Response
   */
  public function actionLogin()
  {
    $this->view->title = 'Войти на сайт';

    if (!Yii::$app->user->isGuest) {
      return $this->goHome();
    }

    $model = new LoginForm();
    if ($model->load(Yii::$app->request->post()) && $model->login()) {
      return $this->goBack();
    }

    return $this->render('login', [
      'model' => $model,
    ]);
  }


  public function actionRegistr()
  {
    $this->view->title = 'Регистрация';
    $user = new RegistrUser();

    if ($user->load(Yii::$app->request->post())) {
      if ($user->validate() && $user->signup()) {

//        $auth = Yii::$app->authManager;
//        $authorRole = $auth->getRole('user');
//        $auth->assign($authorRole, $user->getId());

        Yii::$app->session->setFlash('success', 'Регистрация успешно завершена. Регистрационные данные высланы на ваш email');

        $to = $user->email;

        $subject = "Поздравляем с регистрацией";

        $message = '<p>Поздравляем с регистрацией на сайте whoimi.ru</p>';
        $message .= '<p>Ваш логин: '. $user->username . '</p>';
        $message .= '<p>Ваш пароль: '. $user->password. '</p>';


        $headers  = "Content-type: text/html; charset=utf-8 \r\n";
        $headers .= "From: support@whoimi.ru <support@whoimi.ru>\r\n";
        $headers .= "Reply-To: support@whoimi.ru\r\n";

        mail($to, $subject, $message, $headers);

        return $this->refresh();
      } else {
        Yii::$app->session->setFlash('error', 'Ошибка регистрации');
      }
    } else {
    }

    return $this->render('registr', compact('user'));
  }


  public function actionLogout()
  {
    Yii::$app->user->logout();
    return $this->goHome();
  }


  public function actionDeluser()
  {
    $id = Yii::$app->user->getId();

    Yii::$app->user->logout();
    User::deleteAll('id = :id', [':id' => $id]);

    return $this->goHome();
  }


  public function actionProfile()
  {
    $user = Yii::$app->user->identity;
    $username = $user['username'];
    $balance = r2f($user['balance']);
    $total = $user['total'];
    $remainder = r2f(PAYMENT_LIMIT - $balance);

    return $this->render('profile', compact('username', 'balance', 'total', 'remainder'));
  }


  public function actionSupport()
  {

    $this->view->title = 'Служба поддержки';

    $support = new Support();

    return $this->render('support', compact('support'));
  }

  public function actionSendsupport()
  {
    $answer = '';

    $support = new Support();

    $cause = $_POST['cause'];
    $text = $_POST['text'];
    if ($cause && $text) {
      $support->cause = $cause;
      $support->text = $text;

      if ($support->validate()) {

        $support->id_user = Yii::$app->user->id;
        $support->decision = 0;
        $support->save();
        $answer .= "Ваша заявка будет обработана в ближайшее время";
      } else {
        $answer .= "Validate Error";
      }
    } else {
      $answer .= "Необходимо заполнить все поля формы";
    }

    echo $answer;
  }

  public function actionPdf()
  {
    $user = Yii::$app->user->identity;
    $username = $user['username'];
    $balance = r2f($user['balance']);
    $id = $user['id'];

    $pay = Payment::find()
      ->select(['date', 'pay'])
      ->asArray()
      ->where(['id_user' => $id])
      ->limit(20)
      ->all();


    $mpdf = new \mPDF('utf-8', 'A4', '10', '', 10, 10, 7, 7, 10, 10);
//    CSS
    $stylesheet = file_get_contents('../statement/statement.css');
    $mpdf->WriteHTML($stylesheet, 1);

//    ***********************************************************************************
    $html = '<h1>Детализация выплат: ' . $username . '</h1>';
    $html .= '<p class="balance">Баланс на ' . date("y-m-d H:i") . ': ' . $balance . ' руб.</p>';

    $table = '<table><caption>Последние 20 выплат</caption><tr><th>№</th><th>Сумма выплаты (руб)</th><th>Дата выплаты</th></tr>';
    $i = 1;
    $sum = 0;
    if (empty($pay)) {
      $table .= '<tr><td>$i</td><td>n/a</td><td>n/a</td></tr>';
    } else {
      foreach ($pay as $value) {
        $table .= "<tr><td>$i</td><td>$value[pay]</td><td>$value[date]</td></tr>";
        $sum += $value['pay'];
        $i++;
      }
    }

    $table .= '</table>';
    $html .= $table;

    $html .= '<p>За все время получено ' . $sum . ' руб.</p>';
//    ***********************************************************************************
    $mpdf->WriteHTML($html, 2);
    $mpdf->Output('mpdf.pdf', 'I');
  }

}

views/layouts/_main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function () {
      try {
        w.yaCounter45840108 = new Ya.Metrika({
          id: 45840108,
          clickmap: true,
          trackLinks: true,
          accurateTrackBounce: true,
          webvisor: true,
          trackHash: true
        });
      } catch (e) {
      }
    });

    var n = d.getElementsByTagName("script")[0],
      s = d.createElement("script"),
      f = function () {
        n.parentNode.insertBefore(s, n);
      };
    s.type = "text/javascript";
    s.async = true;
    s.src = "https://mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
      d.addEventListener("DOMContentLoaded", f, false);
    } else {
      f();
    }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript>
  <div><img src="https://mc.yandex.ru/watch/45840108" style="position:absolute; left:-9999px;" alt=""/></div>
</noscript>
<!-- /Yandex.Metrika counter -->

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
  <meta name="google-site-verification" content="M4S4I50MYIEDP-eKANr3GgUD5jvpYTj9p98cTZsrrRA"/>
  <meta charset="<?= Yii::$app->charset ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= Html::csrfMetaTags() ?>
  <title><?= Html::encode($this->title) ?></title>
  <?php $this->head() ?>
</head>

<body>
<?php $this->beginBody() ?>
<!-- ADBLOCK AND ADGUART -->
<div id="spoof-overlay">
  <p>Выключите пожалуйства AdBlock или AdGuart что бы получить доступ к сайту!</p>
</div>

<div class="wrapper">

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="wrap top-menu">
          <ul class="nav nav-pills nav-justified top-menu">
            <li role="presentation"><?= Html::a('Главная', ['/site/index']) ?></li>
            <?php if (!Yii::$app->user->isGuest): ?>
              <li role="presentation"><?= Html::a('Удвой баланс', ['game/lotery']) ?></li>
              <li role="presentation"><?= Html::a('Профиль', ['/user/profile']) ?></li>
              <!--            <li role="presentation">--><? //= Html::a('Выплаты', ['pay/index']) ?><!--</li>-->
              <li role="presentation"><?= Html::a('Выход', ['/user/logout']) ?></li>
            <?php else: ?>
              <li role="presentation"><?= Html::a('Вход', ['user/login']) ?></li>
              <li role="presentation"><?= Html::a('Регистрация', ['user/registr']) ?></li>
            <?php endif; ?>
            <?php if (Yii::$app->user->can('canAdmin')): ?>
              <li role="presentation"><?= Html::a('Admin', ['/admin']) ?></li>
            <?php endif; ?>
            <!--            <li role="presentation">--><? //= Html::a('Поддержка', ['support/support']) ?><!--</li>-->
          </ul>
        </div>
      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
      <div class=" col-md-3">
        <div class="slide">
          <div class="spoof">
            <a href="https://payeer.com/?partner=4900132" target="_blank"><img
                  src="https://payeer.com/bitrix/templates/difiz/img/banner/ru/250x250.gif" alt=""></a>
            <!--            <p>Место для рекламы</p>-->
          </div>
          <div class="spoof">
            <a href="http://bitincome.io/?ref=whoimi" target="_blank"><img
                  src="http://bitincome.io/img/promo/ru/160x600.gif" alt=""></a>
            <!--            <p>Место для рекламы</p>-->
          </div>
          <div class="spoof">
            <!--            <p>Место для рекламы</p>-->
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="content">

          <?= $content ?>

        </div>
      </div>

      <div class=" col-md-3">
        <div class="slide">
          <div class="spoof">
            <a target="_blank" href="https://bitcoset.com/?r=19817"><img src="http://bitcoset.com/images/banners/160x600.gif" alt="Bitcoset Ads" title="Bitcoset Ads" width="160" height="600" border="0" /></a>
            <!--            <p>Место для рекламы</p>-->
          </div>
          <div class="spoof">
            <a href="https://coinmedia.co?ref=14273" title="coinmedia.co"><img src="https://coinmedia.co/img/Banner_200x200.gif" alt="coinmedia.co"></a>
            <!--            <p>Место для рекламы</p>-->
          </div>
          <div class="spoof">
            <!--            <p>Место для рекламы</p>-->
          </div>
        </div>
      </div>
    </div>

    <footer>
      <div class="colum-footer">
        <div class="logo">FreeBie</div>
      </div>
      <div class="colum-footer">
        <a href="http://bitincome.io/?ref=whoimi">Получай от 7% до 13% ежедневно!</a>
      </div>
      <div class="colum-footer">РЕКЛАМНОЕ МЕСТО ПУСТО</div>
    </footer>

  </div>

  <!-- BEGIN JIVOSITE CODE {literal} -->
  <script type='text/javascript'>
    (function () {
      var widget_id = 'oYDf1f9scL';
      var d = document;
      var w = window;

      function l() {
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = '//code.jivosite.com/script/widget/' + widget_id;
        var ss = document.getElementsByTagName('script')[0];
        ss.parentNode.insertBefore(s, ss);
      }

      if (d.readyState == 'complete') {
        l();
      } else {
        if (w.attachEvent) {
          w.attachEvent('onload', l);
        } else {
          w.addEventListener('load', l, false);
        }
      }
    })();</script>
  <!-- {/literal} END JIVOSITE CODE -->

  <?php $this->endBody() ?>
</div>
</body>
</html>
<?php $this->endPage() ?>