models/User.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use Yii;

class User extends ActiveRecord implements \yii\web\IdentityInterface
{

  public static function tableName() {
    return 'users';
  }

  /**
   * @inheritdoc
   */
  public static function findIdentity($id) {
    return static::findOne($id);
  }

  /**
   * @inheritdoc
   */
  public static function findIdentityByAccessToken($token, $type = null) {
//    return static::findOne(['access_token' => $token]);
  }

  /**
   * Finds user by email
   *
   * @param string $email
   * @return static|null
   */
  public static function findByEmail($email) {
    return static::findOne(['email' => $email]);
  }

//  public static function findByWallet($wallet) {
//    return static::findOne(['wallet' => $wallet]);
//  }

  /**
   * @inheritdoc
   */
  public function getId() {
    return $this->id;
  }

  public function getUsername() {
    return $this->username;
  }

  /**
   * @inheritdoc
   */
  public function getAuthKey()  {
    return $this->auth_key;
  }

  /**
   * @inheritdoc
   */
  public function validateAuthKey($authKey) {
    return $this->auth_key === $authKey;
  }

  /**
   * Validates password
   *
   * @param string $password password to validate
   * @return bool if password provided is valid for current user
   */

  public function validatePassword($password) {
//    return true;
    return $this->password == sha1($password);
//    return Yii::$app->security->validatePassword($password, $this->password);
  }



  public function generateAuthKey() {
    $this->auth_key = Yii::$app->security->generateRandomString();
  }


}

models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $auth_key
 * @property string $email
 * @property string $username
 * @property string $wallet
 * @property string $password
 * @property double $balance
 * @property string $ip
 * @property integer $protect
 * @property integer $total
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'password', 'wallet'], 'required'],
            [['balance'], 'number'],
            [['protect', 'total'], 'integer'],
            [['auth_key', 'email', 'wallet', 'password', 'ip'], 'string', 'max' => 255],
            [['username'], 'string', 'max' => 15],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'auth_key' => 'Auth Key',
            'email' => 'Email',
            'username' => 'Username',
            'wallet' => 'Wallet',
            'password' => 'Password',
            'balance' => 'Balance',
            'ip' => 'Ip',
            'protect' => 'Protect',
            'total' => 'Total',
        ];
    }
}

controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: chvs
 * Date: 25.08.2017
 * Time: 22:34
 */

namespace app\controllers;

use app\models\Payment;
use app\models\User;
use app\models\Users;
use app\models\Support;
use Yii;
use app\models\LoginForm;
use app\models\RegistrUser;

class UserController extends AppController
{

  /**
   * User Authorization
   * @return string|\yii\web\Response
   */
  public function actionLogin()
  {
    $this->view->title = 'Войти на сайт';

    if (!Yii::$app->user->isGuest) {
      return $this->goHome();
    }

    $model = new LoginForm();
    if ($model->load(Yii::$app->request->post()) && $model->login()) {
      return $this->goBack();
    }

    return $this->render('login', [
      'model' => $model,
    ]);
  }


  public function actionRegistr()
  {
    $this->view->title = 'Регистрация';
    $user = new RegistrUser();

    if ($user->load(Yii::$app->request->post())) {
      if ($user->validate() && $user->signup()) {

//        $auth = Yii::$app->authManager;
//        $authorRole = $auth->getRole('user');
//        $auth->assign($authorRole, $user->getId());

        Yii::$app->session->setFlash('success', 'Регистрация успешно завершена. Регистрационные данные высланы на ваш email');

        $to = $user->email;

        $subject = "Поздравляем с регистрацией";

        $message = '<p>Поздравляем с регистрацией на сайте whoimi.ru</p>';
        $message .= '<p>Ваш логин: '. $user->username . '</p>';
        $message .= '<p>Ваш пароль: '. $user->password. '</p>';


        $headers  = "Content-type: text/html; charset=utf-8 \r\n";
        $headers .= "From: support@whoimi.ru <support@whoimi.ru>\r\n";
        $headers .= "Reply-To: support@whoimi.ru\r\n";

        mail($to, $subject, $message, $headers);

        return $this->refresh();
      } else {
        Yii::$app->session->setFlash('error', 'Ошибка регистрации');
      }
    } else {
    }

    return $this->render('registr', compact('user'));
  }


  public function actionLogout()
  {
    Yii::$app->user->logout();
    return $this->goHome();
  }


  public function actionDeluser()
  {
    $id = Yii::$app->user->getId();

    Yii::$app->user->logout();
    User::deleteAll('id = :id', [':id' => $id]);

    return $this->goHome();
  }


  public function actionProfile()
  {
    $user = Yii::$app->user->identity;
    $username = $user['username'];
    $balance = r2f($user['balance']);
    $total = $user['total'];
    $remainder = r2f(PAYMENT_LIMIT - $balance);

    return $this->render('profile', compact('username', 'balance', 'total', 'remainder'));
  }


  public function actionSupport()
  {

    $this->view->title = 'Служба поддержки';

    $support = new Support();

    return $this->render('support', compact('support'));
  }

  public function actionSendsupport()
  {
    $answer = '';

    $support = new Support();

    $cause = $_POST['cause'];
    $text = $_POST['text'];
    if ($cause && $text) {
      $support->cause = $cause;
      $support->text = $text;

      if ($support->validate()) {

        $support->id_user = Yii::$app->user->id;
        $support->decision = 0;
        $support->save();
        $answer .= "Ваша заявка будет обработана в ближайшее время";
      } else {
        $answer .= "Validate Error";
      }
    } else {
      $answer .= "Необходимо заполнить все поля формы";
    }

    echo $answer;
  }

  public function actionPdf()
  {
    $user = Yii::$app->user->identity;
    $username = $user['username'];
    $balance = r2f($user['balance']);
    $id = $user['id'];

    $pay = Payment::find()
      ->select(['date', 'pay'])
      ->asArray()
      ->where(['id_user' => $id])
      ->limit(20)
      ->all();


    $mpdf = new \mPDF('utf-8', 'A4', '10', '', 10, 10, 7, 7, 10, 10);
//    CSS
    $stylesheet = file_get_contents('../statement/statement.css');
    $mpdf->WriteHTML($stylesheet, 1);

//    ***********************************************************************************
    $html = '<h1>Детализация выплат: ' . $username . '</h1>';
    $html .= '<p class="balance">Баланс на ' . date("y-m-d H:i") . ': ' . $balance . ' руб.</p>';

    $table = '<table><caption>Последние 20 выплат</caption><tr><th>№</th><th>Сумма выплаты (руб)</th><th>Дата выплаты</th></tr>';
    $i = 1;
    $sum = 0;
    if (empty($pay)) {
      $table .= '<tr><td>$i</td><td>n/a</td><td>n/a</td></tr>';
    } else {
      foreach ($pay as $value) {
        $table .= "<tr><td>$i</td><td>$value[pay]</td><td>$value[date]</td></tr>";
        $sum += $value['pay'];
        $i++;
      }
    }

    $table .= '</table>';
    $html .= $table;

    $html .= '<p>За все время получено ' . $sum . ' руб.</p>';
//    ***********************************************************************************
    $mpdf->WriteHTML($html, 2);
    $mpdf->Output('mpdf.pdf', 'I');
  }

}

views/user/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
//$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-login">
  <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
      'id' => 'login-form',
      'class' => 'form-horizontal',
//      'layout' => 'horizontal',
//      'fieldConfig' => [
//        'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
//        'labelOptions' => ['class' => 'col-lg-1 control-label'],
//      ],
    ]); ?>

    <?= $form->field($model, 'email')->input('email', ['placeholder' => "Email"])->label(false) ?>

    <?= $form->field($model, 'password')->passwordInput()->input( 'password', ['placeholder' => "Password"])->label(false) ?>

    <?= $form->field($model, 'rememberMe')->checkbox([
      'template' => "<div class=\"col-lg-12 rememberMe\">{input} {label}</div>\n<div class=\"col-lg-12\">{error}</div>",
//      'template' => "<div class=\"col-lg-offset-1 col-lg-4\">{input} {label}</div>\n<div class=\"col-lg-7\">{error}</div>",
    ]) ?>

    <div class="form-group">
      <div class="col-lg-12 text-center">
        <?= Html::submitButton('Войти', ['class' => 'btn btn-primary custom-button', 'name' => 'login-button']) ?>
      </div>
    </div>
    <?php ActiveForm::end(); ?>


</div>

views/user/profile.php
<?php

use yii\helpers\Html;

?>

<h1><?= $username ?></h1>
<p>Текущий баланс: <?= $balance ?> руб.</p>
<p>Получено бонусов: <?= $total ?></p>
<p>До выплаты осталось: <?= $remainder ?> руб.</p>

<?= Html::a('Заказать детализацию выплат', ['/user/pdf'], ['class' => 'custom-button long-button'])?>
<?= Html::a('Редактировать аккаунт', ['#'], ['class' => 'custom-button long-button'])?>
<?= Html::a('Написать в поддержку', ['/user/support'], ['class' => 'custom-button long-button write-support'])?>
<?= Html::a('Удалить аккаунт', ['#'], ['class' => 'custom-button long-button js-button-campaign'])?>

<?//= Html::button('Заказать детализацию выплат', ['class' => 'custom-button long-button', 'id' => 'detailing']) ?>
<?//= Html::button('Редактировать аккаунт', ['class' => 'custom-button long-button', 'id' => 'edit-akk']) ?>
<?//= Html::button('Написать в поддержку', ['class' => 'custom-button long-button', 'id' => 'write-support']) ?>
<?//= Html::button('Удалить аккаунт', ['class' => 'custom-button long-button js-button-campaign', 'id' => 'delete-akk']) ?>


<div class="overlay js-overlay-campaign">
  <div class="delete-popup popup js-popup-campaign">
    <h3>Удалить аккаунт?</h3>
    <p>Вы уверенны что хотите удалить аккаунт? Все невыплаченые средства пропадут!</p>
    <form action="site/delete">
      <?= Html::button('Да', ['class' => 'custom-button delete-user-button']) ?>
      <?= Html::button('Нет', ['class' => 'custom-button no-delete-user']) ?>
    </form>
    <div class="close-popup js-close-campaign"></div>
  </div>
</div>

views/user/registr.php
<script src="https://www.google.com/recaptcha/api.js"></script>

<?php
  use yii\widgets\ActiveForm;
  use yii\helpers\Html;
?>

<?php if (Yii::$app->session->hasFlash('success')) : ?>
    <div class="alert alert-success alert-dismissable alert-registr">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <?= Yii::$app->session->getFlash('success') ?>
    </div>

<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('error')) : ?>
  <div class="alert alert-danger alert-dismissable alert-registr">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <?= Yii::$app->session->getFlash('error') ?>
  </div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('warning')) : ?>
  <div class="alert alert-warning alert-dismissable alert-registr">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <?= Yii::$app->session->getFlash('warning') ?>
  </div>
<?php endif; ?>

<h1>Регистрация</h1>


<div class="form">
  <?php $form = ActiveForm::begin(['options' => ['class' => 'form-horizontal', 'id' => 'registrUser']]); ?>
  <div class="login_email">
    <div class="login_icon">
      <i class="fa fa-envelope" aria-hidden="true"></i>
    </div>
    <?= $form->field($user, 'email')->input('email', ['placeholder' => "Email"])->label(false) ?>
  </div>

  <?= $form->field($user, 'username')->input( 'text', ['placeholder' => "Username"])->label(false) ?>

  <?= $form->field($user, 'password')->passwordInput()->input( 'password', ['placeholder' => "Password"])->label(false) ?>

  <?= $form->field($user, 'wallet')->input( 'text', ['placeholder' => "Wallet: P12345678"])->label(false) ?>

  <div class="form-group">
    <div class="col-lg-12 text-center">
      <?= Html::submitButton('Регистрация', ['class' => 'btn btn-primary custom-button', 'name' => 'login-button']) ?>
    </div>
  </div>
</div>


<?php ActiveForm::end(); ?>

views/user/support.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>

<h1>Служба поддержки</h1>

<div class="form-support">
  <?php $form = ActiveForm::begin([
    'id' => 'support-form',
    'class' => 'support-form',
  ]); ?>

  <?= $form->field($support, 'cause')->dropDownList(
    [
      '0' => '',
      '1' => 'Выплата не пришла',
      '2' => 'Не работает лотерея',
      '3' => 'Проблема с капчей',
      '4' => 'Прочее',
    ]
  )->label(true);
  ?>



  <?= $form->field($support, 'text')->textarea(['id' => 'support-t', 'rows' => '7']); ?>

<!--  <div class="col-md-12 text-center clearfix">-->
<!--    <div class="row">-->
      <?= Html::button('Отправить', ['class' => 'btn btn-primary custom-button', 'name' => 'support-button', 'id' => 'send_to_support']) ?>
<!--    </div>-->
<!--  </div>-->
</div>


<div id="support-answer-block"></div>


<?php ActiveForm::end(); ?>